"""Scientific-domain UQ utilities: field metadata, field metrics, domain metrics."""

from __future__ import annotations

from opifex.uncertainty.scientific.domain_metrics import (
    boundary_condition_coverage,
    chemical_accuracy_coverage,
    DomainMetricSummary,
    feasibility_coverage,
    parameter_credible_interval_coverage,
    physics_residual_coverage,
    regret_interval_summary,
    sensor_reliability_summary,
    spectral_coverage,
    UNSUPPORTED_ACTIVE_LEARNING,
    UNSUPPORTED_LIKELIHOOD_FREE,
    UNSUPPORTED_PAC_BAYES,
)
from opifex.uncertainty.scientific.fields import (
    conservation_law_residual_summary,
    FieldMetadata,
    function_space_l2_coverage,
    residual_uncertainty_alignment,
    spatial_calibration_error,
)
from opifex.uncertainty.scientific.polynomial_chaos import (
    evaluate_basis,
    fit_pce_coefficients,
    KarhunenLoeveExpansion,
    KLEConfig,
    pce_mean_variance,
    pce_summary,
    PCESummary,
    PolynomialChaosBasis,
    PolynomialChaosConfig,
    smolyak_sparse_grid,
    SparseGrid,
    StochasticCollocationSurrogate,
    StochasticGalerkinSurrogate,
    tensor_grid_gauss_hermite,
)
from opifex.uncertainty.scientific.probabilistic_numerics import (
    ApplyDiffusionSpec,
    CalibrationSpec,
    CorrectionSpec,
    CubatureRuleSpec,
    DaltonAdapterSpec,
    DenseOutputSamplingSpec,
    DiffeqzooAdapterSpec,
    DiffusionSpec,
    FenrirAdapterSpec,
    InitSchemeSpec,
    IOUPPriorSpec,
    IWPPriorSpec,
    ManifoldUpdateSpec,
    MaternPriorSpec,
    PerturbedStepSolverSpec,
    ProbdiffeqAdapterSpec,
    ProbfindiffAdapterSpec,
    ProbnumAdapterSpec,
    SsmFactSpec,
    StrategySpec,
    TornadoxAdapterSpec,
)
from opifex.uncertainty.scientific.solutions import (
    aggregate_solver_solutions,
    SolutionDistribution,
    summarize_stacked_sample_solution,
)
from opifex.uncertainty.scientific.stochastic_fields import (
    sample_kle_field,
    sample_pce_field,
)
from opifex.uncertainty.scientific.stochastic_galerkin import (
    evaluate_collocation_surrogate,
    evaluate_galerkin_surrogate,
    fit_collocation_surrogate,
    fit_galerkin_surrogate,
)


__all__ = [
    "UNSUPPORTED_ACTIVE_LEARNING",
    "UNSUPPORTED_LIKELIHOOD_FREE",
    "UNSUPPORTED_PAC_BAYES",
    "ApplyDiffusionSpec",
    "CalibrationSpec",
    "CorrectionSpec",
    "CubatureRuleSpec",
    "DaltonAdapterSpec",
    "DenseOutputSamplingSpec",
    "DiffeqzooAdapterSpec",
    "DiffusionSpec",
    "DomainMetricSummary",
    "FenrirAdapterSpec",
    "FieldMetadata",
    "IOUPPriorSpec",
    "IWPPriorSpec",
    "InitSchemeSpec",
    "KLEConfig",
    "KarhunenLoeveExpansion",
    "ManifoldUpdateSpec",
    "MaternPriorSpec",
    "PCESummary",
    "PerturbedStepSolverSpec",
    "PolynomialChaosBasis",
    "PolynomialChaosConfig",
    "ProbdiffeqAdapterSpec",
    "ProbfindiffAdapterSpec",
    "ProbnumAdapterSpec",
    "SolutionDistribution",
    "SparseGrid",
    "SsmFactSpec",
    "StochasticCollocationSurrogate",
    "StochasticGalerkinSurrogate",
    "StrategySpec",
    "TornadoxAdapterSpec",
    "aggregate_solver_solutions",
    "boundary_condition_coverage",
    "chemical_accuracy_coverage",
    "conservation_law_residual_summary",
    "evaluate_basis",
    "evaluate_collocation_surrogate",
    "evaluate_galerkin_surrogate",
    "feasibility_coverage",
    "fit_collocation_surrogate",
    "fit_galerkin_surrogate",
    "fit_pce_coefficients",
    "function_space_l2_coverage",
    "parameter_credible_interval_coverage",
    "pce_mean_variance",
    "pce_summary",
    "physics_residual_coverage",
    "regret_interval_summary",
    "residual_uncertainty_alignment",
    "sample_kle_field",
    "sample_pce_field",
    "sensor_reliability_summary",
    "smolyak_sparse_grid",
    "spatial_calibration_error",
    "spectral_coverage",
    "summarize_stacked_sample_solution",
    "tensor_grid_gauss_hermite",
]
