apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-cache
  namespace: opifex-benchmarking
  labels:
    app.kubernetes.io/name: benchmark-cache
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: opifex-benchmarking
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: fast-cache
