apiVersion: batch/v1
kind: CronJob
metadata:
  name: dataset-sync
  namespace: opifex-benchmarking
  labels:
    app.kubernetes.io/name: dataset-sync
    app.kubernetes.io/component: data-management
    app.kubernetes.io/part-of: opifex-benchmarking
spec:
  schedule: "0 2 * * 0" # Weekly sync on Sunday at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: dataset-sync
            app.kubernetes.io/component: data-management
        spec:
          serviceAccountName: pdebench-service-account
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
            - name: dataset-sync
              image: opifex/pdebench-manager:latest
              imagePullPolicy: Always
              command: ["python", "-m", "pdebench.sync_datasets"]
              env:
                - name: DATASETS_CONFIG_PATH
                  value: "/config/datasets.yaml"
                - name: DATASETS_ROOT
                  value: "/datasets"
                - name: SYNC_MODE
                  value: "incremental"
              resources:
                requests:
                  cpu: "1"
                  memory: "4Gi"
                  ephemeral-storage: "10Gi"
                limits:
                  cpu: "2"
                  memory: "8Gi"
                  ephemeral-storage: "20Gi"
              volumeMounts:
                - name: datasets-config
                  mountPath: /config
                  readOnly: true
                - name: datasets-storage
                  mountPath: /datasets
                - name: tmp-storage
                  mountPath: /tmp
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
          volumes:
            - name: datasets-config
              configMap:
                name: pdebench-datasets-config
            - name: datasets-storage
              persistentVolumeClaim:
                claimName: pdebench-datasets
            - name: tmp-storage
              emptyDir:
                sizeLimit: 5Gi
          nodeSelector:
            kubernetes.io/arch: amd64
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
