apiVersion: batch/v1
kind: CronJob
metadata:
  name: neural-operator-benchmarks
  namespace: opifex-benchmarking
  labels:
    app.kubernetes.io/name: neural-operator-benchmarks
    app.kubernetes.io/component: benchmark-execution
    app.kubernetes.io/part-of: opifex-benchmarking
spec:
  schedule: "0 6 * * 1" # Weekly benchmarks on Monday at 6 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      parallelism: 4 # Run 4 parallel benchmark jobs
      completions: 1
      backoffLimit: 3
      activeDeadlineSeconds: 14400 # 4 hours timeout
      template:
        metadata:
          labels:
            app.kubernetes.io/name: neural-operator-benchmarks
            app.kubernetes.io/component: benchmark-execution
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8080"
            prometheus.io/path: "/metrics"
        spec:
          serviceAccountName: benchmark-executor-service-account
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
            - name: benchmark-executor
              image: opifex/benchmark-executor:latest
              imagePullPolicy: Always
              command: ["python", "-m", "opifex.benchmarking.neural_operators"]
              env:
                - name: BENCHMARK_TYPE
                  value: "neural_operators"
                - name: DATASETS_ROOT
                  value: "/datasets"
                - name: RESULTS_ROOT
                  value: "/results"
                - name: CACHE_ROOT
                  value: "/cache"
                - name: PARALLEL_WORKERS
                  value: "4"
                - name: GPU_MEMORY_FRACTION
                  value: "0.8"
                - name: BENCHMARK_CONFIG
                  value: "/config/neural_operators_config.yaml"
                - name: PYTHONPATH
                  value: "/app"
                - name: CUDA_VISIBLE_DEVICES
                  value: "0"
                - name: JAX_PLATFORMS
                  value: "gpu"
              resources:
                requests:
                  cpu: "4"
                  memory: "16Gi"
                  ephemeral-storage: "50Gi"
                limits:
                  cpu: "8"
                  memory: "32Gi"
                  ephemeral-storage: "100Gi"
                  nvidia.com/gpu: "1"
              volumeMounts:
                - name: benchmark-config
                  mountPath: /config
                  readOnly: true
                - name: datasets-storage
                  mountPath: /datasets
                  readOnly: true
                - name: results-storage
                  mountPath: /results
                - name: cache-storage
                  mountPath: /cache
                - name: tmp-storage
                  mountPath: /tmp
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
          volumes:
            - name: benchmark-config
              configMap:
                name: benchmark-execution-config
            - name: datasets-storage
              persistentVolumeClaim:
                claimName: pdebench-datasets
            - name: results-storage
              persistentVolumeClaim:
                claimName: benchmark-results
            - name: cache-storage
              persistentVolumeClaim:
                claimName: benchmark-cache
            - name: tmp-storage
              emptyDir:
                sizeLimit: 20Gi
          nodeSelector:
            kubernetes.io/arch: amd64
            node-type: gpu-node
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
