apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdebench-datasets
  namespace: opifex-benchmarking
  labels:
    app.kubernetes.io/name: pdebench-storage
    app.kubernetes.io/component: datasets
    app.kubernetes.io/part-of: opifex-benchmarking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: fast-ssd
