apiVersion: v1
kind: Service
metadata:
  name: pdebench-manager-service
  namespace: opifex-benchmarking
  labels:
    app.kubernetes.io/name: pdebench-manager
    app.kubernetes.io/component: dataset-manager
    app.kubernetes.io/part-of: opifex-benchmarking
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: 8080
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app.kubernetes.io/name: pdebench-manager
