apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
    component: scalability
    managed-by: opifex-framework
  name: cluster-autoscaler
  namespace: kube-system
