apiVersion: v1
kind: ConfigMap
metadata:
  name: report-templates
  namespace: opifex-benchmarking
  labels:
    app.kubernetes.io/name: report-templates
    app.kubernetes.io/component: reporting
    app.kubernetes.io/part-of: opifex-benchmarking
data:
  latex_report_template.tex: |
    \documentclass[11pt,a4paper]{article}
    \usepackage[utf8]{inputenc}
    \usepackage{amsmath}
    \usepackage{amsfonts}
    \usepackage{amssymb}
    \usepackage{graphicx}
    \usepackage{booktabs}
    \usepackage{float}
    \usepackage[margin=1in]{geometry}
    \usepackage{hyperref}
    \usepackage{xcolor}
    \usepackage{pgfplots}
    \usepackage{tikz}

    \title{Opifex Framework Benchmark Report}
    \author{Opifex Benchmarking System}
    \date{{{ report_date }}}

    \begin{document}
    \maketitle

    \begin{abstract}
    This report presents comprehensive benchmark results for neural operators and learn-to-optimize algorithms on PDEBench datasets. The analysis includes performance comparisons, accuracy metrics, and computational efficiency evaluations across multiple methods and datasets.
    \end{abstract}

    \section{Executive Summary}

    \subsection{Key Findings}
    \begin{itemize}
    {% for finding in key_findings %}
    \item {{ finding }}
    {% endfor %}
    \end{itemize}

    \subsection{Performance Highlights}
    \begin{table}[H]
    \centering
    \begin{tabular}{@{}lcccc@{}}
    \toprule
    \textbf{Method} & \textbf{Best Dataset} & \textbf{Speedup} & \textbf{Accuracy (MSE)} & \textbf{Memory Efficiency} \\
    \midrule
    {% for highlight in performance_highlights %}
    {{ highlight.method }} & {{ highlight.dataset }} & {{ "%.1f"|format(highlight.speedup) }}$\times$ & {{ "%.2e"|format(highlight.accuracy) }} & {{ "%.1f"|format(highlight.memory_efficiency) }}\% \\
    {% endfor %}
    \bottomrule
    \end{tabular}
    \caption{Top performing methods across datasets}
    \label{tab:performance_highlights}
    \end{table}

    \section{Neural Operator Results}

    {% for dataset_name, results in neural_operator_results.items() %}
    \subsection{{{ dataset_name.replace('_', ' ').title() }} Dataset}

    \begin{figure}[H]
    \centering
    \includegraphics[width=0.8\textwidth]{plots/{{ dataset_name }}_performance_comparison.pdf}
    \caption{Performance comparison for {{ dataset_name.replace('_', ' ') }} dataset}
    \label{fig:{{ dataset_name }}_performance}
    \end{figure}

    \begin{table}[H]
    \centering
    \begin{tabular}{@{}lcccc@{}}
    \toprule
    \textbf{Method} & \textbf{Execution Time (s)} & \textbf{MSE} & \textbf{Memory (GB)} & \textbf{GPU Util. (\%)} \\
    \midrule
    {% for result in results %}
    {{ result.method_name }} & {{ "%.2f"|format(result.execution_time) }} & {{ "%.2e"|format(result.mse) }} & {{ "%.2f"|format(result.memory_usage) }} & {{ "%.1f"|format(result.gpu_utilization) }} \\
    {% endfor %}
    \bottomrule
    \end{tabular}
    \caption{Detailed results for {{ dataset_name.replace('_', ' ') }} dataset}
    \label{tab:{{ dataset_name }}_results}
    \end{table}
    {% endfor %}

    \section{Learn-to-Optimize Results}

    {% for algorithm_type, results in l2o_results.items() %}
    \subsection{{{ algorithm_type.replace('_', ' ').title() }} Algorithm}

    \begin{figure}[H]
    \centering
    \includegraphics[width=0.8\textwidth]{plots/{{ algorithm_type }}_convergence.pdf}
    \caption{Convergence analysis for {{ algorithm_type.replace('_', ' ') }} algorithm}
    \label{fig:{{ algorithm_type }}_convergence}
    \end{figure}

    Key performance metrics:
    \begin{itemize}
    {% for metric_name, metric_value in results.performance_metrics.items() %}
    \item \textbf{{{ metric_name.replace('_', ' ').title() }}}: {{ metric_value }}
    {% endfor %}
    \end{itemize}
    {% endfor %}

    \section{Comparative Analysis}

    \begin{figure}[H]
    \centering
    \includegraphics[width=0.9\textwidth]{plots/speedup_vs_accuracy.pdf}
    \caption{Speedup vs. Accuracy trade-off analysis}
    \label{fig:speedup_accuracy}
    \end{figure}

    \section{Conclusions and Recommendations}

    \subsection{Best Practices}
    \begin{itemize}
    {% for practice in best_practices %}
    \item {{ practice }}
    {% endfor %}
    \end{itemize}

    \subsection{Future Work}
    \begin{itemize}
    {% for item in future_work %}
    \item {{ item }}
    {% endfor %}
    \end{itemize}

    \section{Technical Details}

    \subsection{Experimental Setup}
    \begin{itemize}
    \item \textbf{Hardware}: {{ experimental_setup.hardware }}
    \item \textbf{Software}: {{ experimental_setup.software }}
    \item \textbf{Framework Version}: {{ experimental_setup.framework_version }}
    \item \textbf{Datasets}: {{ experimental_setup.datasets|join(', ') }}
    \end{itemize}

    \subsection{Metrics Definition}
    \begin{itemize}
    \item \textbf{Execution Time}: Wall-clock time for training and inference
    \item \textbf{Memory Usage}: Peak GPU memory consumption during execution
    \item \textbf{Accuracy (MSE)}: Mean squared error on test set
    \item \textbf{Speedup}: Ratio of traditional solver time to neural method time
    \end{itemize}

    \end{document}

  html_report_template.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Opifex Benchmark Report - {{ report_date }}</title>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            .metric-card { transition: transform 0.2s; }
            .metric-card:hover { transform: translateY(-5px); }
            .performance-highlight { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
            .chart-container { height: 400px; margin: 20px 0; }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <div class="container-fluid">
                <span class="navbar-brand h1">Opifex Benchmark Report</span>
                <span class="navbar-text">{{ report_date }}</span>
            </div>
        </nav>

        <div class="container-fluid mt-4">
            <div class="row">
                <div class="col-12">
                    <div class="card performance-highlight text-white mb-4">
                        <div class="card-body">
                            <h2 class="card-title">Executive Summary</h2>
                            <p class="card-text">Comprehensive benchmark analysis of {{ total_experiments }} experiments across {{ total_datasets }} datasets.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mb-4">
                {% for highlight in performance_highlights %}
                <div class="col-md-3">
                    <div class="card metric-card h-100">
                        <div class="card-body text-center">
                            <h5 class="card-title">{{ highlight.method }}</h5>
                            <h3 class="text-primary">{{ "%.1f"|format(highlight.speedup) }}×</h3>
                            <p class="card-text">Speedup on {{ highlight.dataset }}</p>
                            <small class="text-muted">MSE: {{ "%.2e"|format(highlight.accuracy) }}</small>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>Performance vs Accuracy</h5>
                        </div>
                        <div class="card-body">
                            <div id="speedup-accuracy-chart" class="chart-container"></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>Memory Efficiency</h5>
                        </div>
                        <div class="card-body">
                            <div id="memory-efficiency-chart" class="chart-container"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mt-4">
                {% for dataset_name, results in neural_operator_results.items() %}
                <div class="col-12 mb-4">
                    <div class="card">
                        <div class="card-header">
                            <h5>{{ dataset_name.replace('_', ' ').title() }} Dataset Results</h5>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Method</th>
                                            <th>Execution Time (s)</th>
                                            <th>MSE</th>
                                            <th>Memory (GB)</th>
                                            <th>GPU Utilization (%)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for result in results %}
                                        <tr>
                                            <td>{{ result.method_name }}</td>
                                            <td>{{ "%.2f"|format(result.execution_time) }}</td>
                                            <td>{{ "%.2e"|format(result.mse) }}</td>
                                            <td>{{ "%.2f"|format(result.memory_usage) }}</td>
                                            <td>{{ "%.1f"|format(result.gpu_utilization) }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div id="{{ dataset_name }}-chart" class="chart-container"></div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <script>
            // Speedup vs Accuracy Chart
            var speedupAccuracyData = [
                {% for highlight in performance_highlights %}
                {
                    x: [{{ highlight.speedup }}],
                    y: [{{ highlight.accuracy }}],
                    mode: 'markers+text',
                    text: ['{{ highlight.method }}'],
                    textposition: 'top center',
                    marker: { size: 12, color: 'rgb(102, 126, 234)' },
                    name: '{{ highlight.method }}'
                },
                {% endfor %}
            ];

            var speedupAccuracyLayout = {
                title: 'Speedup vs Accuracy Trade-off',
                xaxis: { title: 'Speedup (×)', type: 'log' },
                yaxis: { title: 'Accuracy (MSE)', type: 'log' },
                showlegend: false
            };

            Plotly.newPlot('speedup-accuracy-chart', speedupAccuracyData, speedupAccuracyLayout);

            // Memory Efficiency Chart
            var memoryData = [{
                x: [{% for highlight in performance_highlights %}'{{ highlight.method }}',{% endfor %}],
                y: [{% for highlight in performance_highlights %}{{ highlight.memory_efficiency }},{% endfor %}],
                type: 'bar',
                marker: { color: 'rgb(118, 75, 162)' }
            }];

            var memoryLayout = {
                title: 'Memory Efficiency by Method',
                xaxis: { title: 'Method' },
                yaxis: { title: 'Memory Efficiency (%)' }
            };

            Plotly.newPlot('memory-efficiency-chart', memoryData, memoryLayout);

            // Dataset-specific charts
            {% for dataset_name, results in neural_operator_results.items() %}
            var {{ dataset_name }}Data = [{
                x: [{% for result in results %}'{{ result.method_name }}',{% endfor %}],
                y: [{% for result in results %}{{ result.execution_time }},{% endfor %}],
                type: 'bar',
                name: 'Execution Time',
                yaxis: 'y',
                marker: { color: 'rgb(102, 126, 234)' }
            }, {
                x: [{% for result in results %}'{{ result.method_name }}',{% endfor %}],
                y: [{% for result in results %}{{ result.mse }},{% endfor %}],
                type: 'scatter',
                mode: 'markers',
                name: 'MSE',
                yaxis: 'y2',
                marker: { color: 'rgb(255, 126, 84)', size: 10 }
            }];

            var {{ dataset_name }}Layout = {
                title: '{{ dataset_name.replace('_', ' ').title() }} Performance',
                xaxis: { title: 'Method' },
                yaxis: { title: 'Execution Time (s)', side: 'left' },
                yaxis2: { title: 'MSE', side: 'right', overlaying: 'y', type: 'log' }
            };

            Plotly.newPlot('{{ dataset_name }}-chart', {{ dataset_name }}Data, {{ dataset_name }}Layout);
            {% endfor %}
        </script>

        <footer class="bg-light text-center text-lg-start mt-5">
            <div class="text-center p-3">
                © 2025 Opifex Framework - Generated by Automated Benchmarking System
            </div>
        </footer>
    </body>
    </html>
