apiVersion: v1
kind: ConfigMap
metadata:
  name: security-context-config
  namespace: opifex-system
  labels:
    app.kubernetes.io/name: security-context
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: opifex-container-orchestration
data:
  security-context.yaml: |
    # Default Security Context for Opifex Containers
    # Phase 7.1: Container Orchestration - Security Standards

    securityContext:
      # Run as non-root user
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

      # Security capabilities
      capabilities:
        drop:
          - ALL
        add:
          - SYS_ADMIN  # Required for NVIDIA runtime

      # Security policies
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false  # Required for GPU libraries
      privileged: false

      # SELinux options
      seLinuxOptions:
        level: "s0:c123,c456"

      # Seccomp profile
      seccompProfile:
        type: RuntimeDefault

      # AppArmor profile
      appArmorProfile:
        type: RuntimeDefault

    # Container-specific security context
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add:
          - SYS_ADMIN
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
