apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opifex-benchmarking-core-binding
  labels:
    app.kubernetes.io/name: opifex-benchmarking-core-binding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: opifex-benchmarking
subjects:
  - kind: ServiceAccount
    name: benchmark-executor-service-account
    namespace: opifex-benchmarking
  - kind: ServiceAccount
    name: pdebench-service-account
    namespace: opifex-benchmarking
roleRef:
  kind: ClusterRole
  name: opifex-benchmarking-core
  apiGroup: rbac.authorization.k8s.io
