apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opifex-benchmarking-core
  labels:
    app.kubernetes.io/name: opifex-benchmarking-core
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: opifex-benchmarking
rules:
  # Pod and Job management for benchmark execution
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]

  # ConfigMap and Secret access for configuration
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

  # Events for monitoring and debugging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create"]

  # Metrics and monitoring
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]

  # GPU resource monitoring
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
