apiVersion: v1
kind: Service
metadata:
  name: minio-neural-functionals
  namespace: opifex-community
  labels:
    app.kubernetes.io/name: minio-neural-functionals
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/part-of: opifex-community
spec:
  selector:
    app.kubernetes.io/name: minio-neural-functionals
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: console
      port: 9001
      targetPort: 9001
      protocol: TCP
  type: ClusterIP
