r"""Tests for the per-atom energy scale-shift (E0 + output normaliser).

The :class:`~opifex.neural.atomistic.scale_shift.AtomicScaleShift` closes the
deferred per-element reference-energy / output-normaliser gap documented in
:class:`~opifex.neural.atomistic.heads.energy.EnergyHead`. It follows the MACE
``ScaleShiftBlock`` affine map ``E_phys = scale * E_raw + n_atoms * shift``
(Batzner et al. 2022, NequIP, arXiv:2101.03164; the ``../mace``
``mace/modules/blocks.py`` ``ScaleShiftBlock`` and
``mace/modules/utils.py`` ``compute_mean_std_atomic_inter_energy`` statistics).

Load-bearing checks:

* :func:`fit_atomic_scale_shift` recovers a known ``shift``/``scale`` from
  synthetic energies generated by the affine model;
* ``apply`` and ``invert`` round-trip;
* an :class:`EnergyHead` wired with a scale-shift stays an E(3)/permutation
  invariant scalar and is ``jit``/``grad``/``vmap`` clean.
"""

from __future__ import annotations

import jax
import jax.numpy as jnp
from flax import nnx
from jaxtyping import Array  # noqa: TC002

from opifex.core.quantum.molecular_system import MolecularSystem
from opifex.core.quantum.protocols import RadiusNeighborList
from opifex.neural.atomistic import AtomisticModel
from opifex.neural.atomistic.heads import EnergyHead, ForcesHead
from opifex.neural.atomistic.scale_shift import (
    AtomicScaleShift,
    fit_atomic_scale_shift,
)
from opifex.neural.equivariant import scatter_sum


def _node_features(n_atoms: int = 3, feature_dim: int = 8) -> dict[str, Array]:
    """A small deterministic ``node_features`` embedding for head tests."""
    key = jax.random.PRNGKey(0)
    return {"node_features": jax.random.normal(key, (n_atoms, feature_dim))}


class TestFitAtomicScaleShift:
    def test_recovers_known_shift_and_scale(self) -> None:
        """Energies = ``n_atoms*shift + residual`` recover shift and residual std.

        ``shift`` is the mean per-atom energy and ``scale`` is the standard
        deviation of the per-configuration residual ``E - n_atoms*shift`` (the
        MACE ``compute_mean_std_atomic_inter_energy`` recipe, with the residual
        taken over total -- not per-atom -- energy as the spec defines).
        """
        with jax.enable_x64(True):
            key = jax.random.PRNGKey(1)
            n_configs = 4096
            atom_counts = jnp.full((n_configs,), 4.0, dtype=jnp.float64)
            true_shift = -1.7
            true_scale = 0.8
            residual = true_scale * jax.random.normal(key, (n_configs,))
            energies = atom_counts * true_shift + residual

            fitted = fit_atomic_scale_shift(energies, atom_counts)

            assert jnp.allclose(fitted.shift, true_shift, atol=0.05)
            assert jnp.allclose(fitted.scale, true_scale, atol=0.05)

    def test_shift_is_mean_of_per_atom_energy(self) -> None:
        """``shift = mean(E / n_atoms)`` -- the MACE per-atom-energy mean."""
        with jax.enable_x64(True):
            energies = jnp.asarray([6.0, 10.0, 8.0], dtype=jnp.float64)
            atom_counts = jnp.asarray([3.0, 5.0, 4.0], dtype=jnp.float64)
            fitted = fit_atomic_scale_shift(energies, atom_counts)
            expected_shift = jnp.mean(energies / atom_counts)
            assert jnp.allclose(fitted.shift, expected_shift, atol=1e-9)

    def test_scale_is_std_of_residual_energy(self) -> None:
        """``scale = std(E - n_atoms*shift)`` -- the residual normaliser."""
        with jax.enable_x64(True):
            energies = jnp.asarray([6.0, 11.0, 7.5, 9.0], dtype=jnp.float64)
            atom_counts = jnp.asarray([3.0, 5.0, 4.0, 4.0], dtype=jnp.float64)
            fitted = fit_atomic_scale_shift(energies, atom_counts)
            shift = jnp.mean(energies / atom_counts)
            expected_scale = jnp.std(energies - atom_counts * shift)
            assert jnp.allclose(fitted.scale, expected_scale, atol=1e-9)


class TestAtomicScaleShiftRoundTrip:
    def test_apply_then_invert_is_identity(self) -> None:
        """``invert(apply(e)) == e`` for any raw energy / atom count."""
        with jax.enable_x64(True):
            scale_shift = AtomicScaleShift(
                scale=jnp.asarray(0.7, dtype=jnp.float64),
                shift=jnp.asarray(-2.1, dtype=jnp.float64),
            )
            raw_energy = jnp.asarray(3.3, dtype=jnp.float64)
            n_atoms = 5
            physical = scale_shift.apply(raw_energy, n_atoms)
            recovered = scale_shift.invert(physical, n_atoms)
            assert jnp.allclose(recovered, raw_energy, atol=1e-9)

    def test_apply_matches_affine_formula(self) -> None:
        """``apply`` is exactly ``scale*E_raw + n_atoms*shift``."""
        with jax.enable_x64(True):
            scale_shift = AtomicScaleShift(
                scale=jnp.asarray(2.0, dtype=jnp.float64),
                shift=jnp.asarray(1.5, dtype=jnp.float64),
            )
            raw_energy = jnp.asarray(4.0, dtype=jnp.float64)
            n_atoms = 3
            expected = 2.0 * 4.0 + 3 * 1.5
            assert jnp.allclose(scale_shift.apply(raw_energy, n_atoms), expected, atol=1e-9)

    def test_identity_default_is_no_op(self) -> None:
        """The identity scale-shift leaves the raw energy unchanged."""
        scale_shift = AtomicScaleShift.identity()
        raw_energy = jnp.asarray(3.14)
        assert jnp.allclose(scale_shift.apply(raw_energy, 7), raw_energy)


class TestEnergyHeadWithScaleShift:
    def test_default_head_unchanged(self) -> None:
        """``scale_shift=None`` reproduces the bare sum-of-atomic-energies."""
        rngs = nnx.Rngs(0)
        plain = EnergyHead(feature_dim=8, rngs=rngs)
        system = MolecularSystem(
            atomic_numbers=jnp.asarray([8, 1, 1]),
            positions=jnp.zeros((3, 3)),
        )
        embeddings = _node_features()
        graph = (jnp.asarray([0]), jnp.asarray([1]))
        baseline = plain(system, graph, embeddings)["energy"]

        rngs2 = nnx.Rngs(0)
        identity_head = EnergyHead(
            feature_dim=8, scale_shift=AtomicScaleShift.identity(), rngs=rngs2
        )
        with_identity = identity_head(system, graph, embeddings)["energy"]
        assert jnp.allclose(baseline, with_identity, atol=1e-6)

    def test_scale_shift_changes_energy_by_affine_map(self) -> None:
        """A non-trivial scale-shift transforms the summed energy affinely."""
        rngs = nnx.Rngs(3)
        plain = EnergyHead(feature_dim=8, rngs=rngs)
        scale_shift = AtomicScaleShift(scale=jnp.asarray(2.0), shift=jnp.asarray(0.5))
        rngs2 = nnx.Rngs(3)
        shifted = EnergyHead(feature_dim=8, scale_shift=scale_shift, rngs=rngs2)
        system = MolecularSystem(
            atomic_numbers=jnp.asarray([8, 1, 1]),
            positions=jnp.zeros((3, 3)),
        )
        embeddings = _node_features()
        graph = (jnp.asarray([0]), jnp.asarray([1]))
        raw = plain(system, graph, embeddings)["energy"]
        physical = shifted(system, graph, embeddings)["energy"]
        expected = 2.0 * raw + 3 * 0.5
        assert jnp.allclose(physical, expected, atol=1e-5)

    def test_scale_shift_head_is_jit_grad_vmap_clean(self) -> None:
        """A scale-shifted head differentiates and batches without error."""
        scale_shift = AtomicScaleShift(scale=jnp.asarray(1.3), shift=jnp.asarray(-0.4))
        head = EnergyHead(feature_dim=8, scale_shift=scale_shift, rngs=nnx.Rngs(0))
        graphdef, state = nnx.split(head)
        system = MolecularSystem(
            atomic_numbers=jnp.asarray([8, 1, 1]),
            positions=jnp.zeros((3, 3)),
        )
        graph = (jnp.asarray([0]), jnp.asarray([1]))

        def energy_of(node_features: Array) -> Array:
            rebuilt = nnx.merge(graphdef, state)
            return rebuilt(system, graph, {"node_features": node_features})["energy"]

        base = _node_features()["node_features"]
        jitted = jax.jit(energy_of)
        assert jnp.isfinite(jitted(base))

        gradient = jax.grad(lambda nf: energy_of(nf) ** 2)(base)
        assert gradient.shape == base.shape
        assert bool(jnp.all(jnp.isfinite(gradient)))

        batch = jnp.stack([base, base + 0.1])
        energies = jax.vmap(energy_of)(batch)
        assert energies.shape == (2,)
        assert bool(jnp.all(jnp.isfinite(energies)))


class _ToyBackbone(nnx.Module):
    """Minimal invariant backbone (cutoff-weighted coordination MLP)."""

    def __init__(self, *, hidden: int = 8, rngs: nnx.Rngs) -> None:
        super().__init__()
        self.cutoff = 3.0
        self.linear_in = nnx.Linear(1, hidden, rngs=rngs)
        self.linear_out = nnx.Linear(hidden, hidden, rngs=rngs)

    def __call__(self, system: MolecularSystem, graph: tuple[Array, Array]) -> dict[str, Array]:
        senders, receivers = graph
        valid = senders >= 0
        safe_senders = jnp.where(valid, senders, 0)
        safe_receivers = jnp.where(valid, receivers, 0)
        deltas = system.positions[safe_senders] - system.positions[safe_receivers]
        distances = jnp.linalg.norm(deltas + 1e-12, axis=-1)
        envelope = jnp.where(valid, jnp.clip(1.0 - distances / self.cutoff, 0.0, None), 0.0)
        coordination = scatter_sum(envelope[:, None], safe_receivers, num_segments=system.n_atoms)
        features = nnx.tanh(self.linear_in(coordination))
        return {"node_features": nnx.tanh(self.linear_out(features))}


def _assembled_model(scale_shift: AtomicScaleShift | None) -> AtomisticModel:
    rngs = nnx.Rngs(0)
    heads: dict[str, object] = {
        "energy": EnergyHead(feature_dim=8, scale_shift=scale_shift, rngs=rngs),
        "forces": ForcesHead(),
    }
    return AtomisticModel(
        backbone=_ToyBackbone(rngs=rngs),
        heads=heads,  # type: ignore[arg-type]
        neighbor_list=RadiusNeighborList(cutoff=3.0),
        max_edges=32,
    )


def _water_x64() -> MolecularSystem:
    return MolecularSystem(
        atomic_numbers=jnp.asarray([8, 1, 1]),
        positions=jnp.asarray(
            [[0.0, 0.0, 0.0], [0.96, 0.0, 0.0], [-0.24, 0.93, 0.0]], dtype=jnp.float64
        ),
    )


class TestScaleShiftInAssembledModel:
    """The scale-shift composes through the conservative force head."""

    def test_forces_unchanged_by_constant_shift(self) -> None:
        """A constant per-atom ``shift`` is geometry-independent, so it leaves the
        conservative forces (``-grad(E)``) unchanged; only ``scale`` rescales them."""
        with jax.enable_x64(True):
            system = _water_x64()
            plain = _assembled_model(None)
            shift_only = _assembled_model(
                AtomicScaleShift(
                    scale=jnp.asarray(1.0, dtype=jnp.float64),
                    shift=jnp.asarray(-3.5, dtype=jnp.float64),
                )
            )
            assert jnp.allclose(plain(system)["forces"], shift_only(system)["forces"], atol=1e-9)

    def test_forces_rescaled_by_scale(self) -> None:
        """A pure ``scale`` multiplies the conservative forces by the same factor."""
        with jax.enable_x64(True):
            system = _water_x64()
            plain = _assembled_model(None)
            scaled = _assembled_model(
                AtomicScaleShift(
                    scale=jnp.asarray(2.5, dtype=jnp.float64),
                    shift=jnp.asarray(0.0, dtype=jnp.float64),
                )
            )
            assert jnp.allclose(scaled(system)["forces"], 2.5 * plain(system)["forces"], atol=1e-8)

    def test_assembled_model_is_jit_grad_vmap_clean(self) -> None:
        """The scale-shifted, force-producing model is jit/grad/vmap clean."""
        model = _assembled_model(AtomicScaleShift(scale=jnp.asarray(1.4), shift=jnp.asarray(-2.0)))
        graphdef, state = nnx.split(model)
        atomic_numbers = jnp.asarray([8, 1, 1])
        base = jnp.asarray([[0.0, 0.0, 0.0], [0.96, 0.0, 0.0], [-0.24, 0.93, 0.0]])

        def energy_for(positions: Array) -> Array:
            rebuilt = nnx.merge(graphdef, state)
            system = MolecularSystem(atomic_numbers=atomic_numbers, positions=positions)
            return rebuilt(system)["energy"]

        assert jnp.isfinite(jax.jit(energy_for)(base))
        gradient = jax.grad(lambda p: energy_for(p) ** 2)(base)
        assert bool(jnp.all(jnp.isfinite(gradient)))
        energies = jax.vmap(energy_for)(jnp.stack([base, base + 0.1]))
        assert energies.shape == (2,)
