apiVersion: apps/v1
kind: Deployment
metadata:
  name: consent-management-service
  namespace: security
  labels:
    app.kubernetes.io/name: consent-management
    app.kubernetes.io/component: gdpr-compliance
    app.kubernetes.io/part-of: opifex-enterprise-security
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: consent-management
  template:
    metadata:
      labels:
        app.kubernetes.io/name: consent-management
        app.kubernetes.io/component: gdpr-compliance
    spec:
      serviceAccountName: consent-management-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1002
        runAsGroup: 1002
        fsGroup: 1002
      containers:
        - name: consent-service
          image: harbor.opifex.enterprise.com/compliance/consent-management:v1.1.0
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: consent-database-secret
                  key: connection-string
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: gdpr-encryption-secret
                  key: consent-encryption-key
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: connection-string
            - name: AUDIT_WEBHOOK_URL
              value: "https://audit.compliance.internal/webhooks/consent"
            - name: KEYCLOAK_BASE_URL
              value: "https://auth.opifex.enterprise.com"
            - name: WITHDRAWAL_GRACE_PERIOD
              value: "30d"
            - name: CONSENT_REFRESH_PERIOD
              value: "365d"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
