apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gdpr-audit-storage-pvc
  namespace: security
  labels:
    app.kubernetes.io/name: gdpr-audit-storage
    app.kubernetes.io/component: gdpr-compliance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
