apiVersion: batch/v1
kind: CronJob
metadata:
  name: consent-refresh-reminder
  namespace: security
  labels:
    app.kubernetes.io/name: consent-refresh-reminder
    app.kubernetes.io/component: gdpr-compliance
    app.kubernetes.io/part-of: opifex-enterprise-security
spec:
  schedule: "0 8 1 * *" # Monthly on 1st at 8 AM UTC
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: consent-management-sa
          restartPolicy: Never
          containers:
            - name: consent-reminder
              image: harbor.opifex.enterprise.com/compliance/consent-reminder:v1.0.2
              env:
                - name: SMTP_SERVER
                  valueFrom:
                    secretKeyRef:
                      name: email-secret
                      key: smtp-server
                - name: SMTP_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: email-secret
                      key: username
                - name: SMTP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: email-secret
                      key: password
                - name: CONSENT_SERVICE_URL
                  value: "http://consent-management-service:8080"
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "25m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"
