apiVersion: v1
kind: Service
metadata:
  name: security-monitoring-service
  namespace: security
  labels:
    app.kubernetes.io/name: security-monitoring-service
    app.kubernetes.io/component: soc2-controls
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: websocket
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app.kubernetes.io/name: security-monitoring
