apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-response-orchestrator
  namespace: security
  labels:
    app.kubernetes.io/name: incident-response
    app.kubernetes.io/component: soc2-controls
    app.kubernetes.io/part-of: opifex-enterprise-security
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: incident-response
  template:
    metadata:
      labels:
        app.kubernetes.io/name: incident-response
        app.kubernetes.io/component: soc2-controls
    spec:
      serviceAccountName: incident-response-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1006
        runAsGroup: 1006
        fsGroup: 1006
      containers:
        - name: incident-orchestrator
          image: harbor.opifex.enterprise.com/security/incident-response:v1.3.0
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: incident-database-secret
                  key: connection-string
            - name: NOTIFICATION_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: webhook-url
            - name: KEYCLOAK_BASE_URL
              value: "https://auth.opifex.enterprise.com"
            - name: ELASTICSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: connection-string
            - name: RESPONSE_TIME_CRITICAL
              value: "15m"
            - name: RESPONSE_TIME_HIGH
              value: "1h"
            - name: LOG_LEVEL
              value: "INFO"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          volumeMounts:
            - name: incident-config
              mountPath: /etc/incident-response
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: incident-config
          configMap:
            name: soc2-compliance-config
