apiVersion: v1
kind: Service
metadata:
  name: audit-log-processor-service
  namespace: security
  labels:
    app.kubernetes.io/name: audit-log-processor-service
    app.kubernetes.io/component: soc2-controls
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: audit-log-processor
