apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-audit-sa
  namespace: security
  labels:
    app.kubernetes.io/name: compliance-audit-sa
    app.kubernetes.io/component: soc2-controls
