apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: opifex-security
  name: keycloak-postgres-role
  labels:
    app: keycloak-postgres
    component: database
    tier: security
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
