# PostgreSQL Database Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres
  namespace: opifex-security
  labels:
    app: keycloak-postgres
    component: database
    tier: security
type: Opaque
data:
  # Base64 encoded values - Replace with actual credentials before deployment
  # Default: keycloak / secure-password-123
  username: a2V5Y2xvYWs=
  password: c2VjdXJlLXBhc3N3b3JkLTEyMw==
