# Keycloak Admin Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: opifex-security
  labels:
    app: keycloak
    component: identity-management
    tier: security
type: Opaque
data:
  # Base64 encoded values - Replace with actual credentials before deployment
  # Default: admin / change-me-please
  username: YWRtaW4=
  password: Y2hhbmdlLW1lLXBsZWFzZQ==
