apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-postgres
  namespace: opifex-security
  labels:
    app: keycloak-postgres
    component: database
    tier: security
automountServiceAccountToken: false
