apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: opifex-security
  labels:
    app: keycloak
    component: identity-management
    tier: security
automountServiceAccountToken: true
