apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neural-operator-hpa
  namespace: opifex-system
  labels:
    app: neural-operator-trainer
    component: scalability
    managed-by: opifex-framework
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neural-operator-trainer
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: nvidia.com/gpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
    - type: Pods
      pods:
        metric:
          name: opifex_training_queue_length
        target:
          type: AverageValue
          averageValue: "5"
    - type: Pods
      pods:
        metric:
          name: opifex_neural_operator_batch_size
        target:
          type: AverageValue
          averageValue: "32"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600 # Longer stabilization for training
      policies:
        - type: Percent
          value: 20
          periodSeconds: 120
        - type: Pods
          value: 1
          periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 100
          periodSeconds: 120
        - type: Pods
          value: 3
          periodSeconds: 120
      selectPolicy: Max
