apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-tracking-server
  namespace: opifex-mlops
  labels:
    app.kubernetes.io/name: mlflow-tracking-server
    app.kubernetes.io/component: tracking-server
  annotations:
    opifex.framework/description: "Service account for MLflow tracking server with GPU access"
