apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-minio
  namespace: opifex-mlops
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/instance: mlflow-minio
  annotations:
    opifex.framework/description: "Service account for MinIO object storage"
