# Custom Resource Definition for GPU Workload Profiles
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gpuprofiles.opifex.io
spec:
  group: opifex.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gpuType:
                  type: string
                  enum: ["V100", "P100", "A100", "H100", "RTX3090"]
                memoryFraction:
                  type: number
                  minimum: 0.1
                  maximum: 1.0
                batchSizeMultiplier:
                  type: number
                  minimum: 0.5
                  maximum: 3.0
                workloadType:
                  type: string
                  enum: ["training", "inference", "benchmarking"]
                optimizationFlags:
                  type: array
                  items:
                    type: string
              required:
                - gpuType
                - memoryFraction
                - workloadType
            status:
              type: object
              properties:
                phase:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
  scope: Namespaced
  names:
    plural: gpuprofiles
    singular: gpuprofile
    kind: GPUProfile
    shortNames:
      - gpup
