apiVersion: v1
kind: ServiceAccount
metadata:
  name: unified-mlops-api
  namespace: opifex-mlops
  labels:
    app.kubernetes.io/name: unified-mlops-api
    app.kubernetes.io/component: api-gateway
  annotations:
    opifex.framework/description: "Service account for unified MLOps API with backend access"
