# Neural Operators Lead with elevated permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neural-operators-lead-binding
  labels:
    opifex.local/research-group: "neural-operators"
    opifex.local/role-type: "research-lead"
subjects:
  - kind: User
    name: "university-saml.neural-lead@university.edu"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: opifex-research-lead
  apiGroup: rbac.authorization.k8s.io
