# GPU Node Access Controls
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opifex-gpu-access
  labels:
    opifex.local/resource-type: "gpu"
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    resourceNames: ["gpu-*", "training-*"]
