# GPU Access Bindings
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opifex-gpu-access-binding
  labels:
    opifex.local/resource-type: "gpu"
subjects:
  # Research leads get enhanced GPU access
  - kind: User
    name: "university-saml.neural-lead@university.edu"
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: "university-saml.physics-lead@university.edu"
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: "university-saml.fluid-lead@university.edu"
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: "university-saml.materials-lead@university.edu"
    apiGroup: rbac.authorization.k8s.io
  # Service accounts for automated GPU resource management
  - kind: ServiceAccount
    name: opifex-training-service
    namespace: opifex-training
  - kind: ServiceAccount
    name: opifex-api-server
    namespace: opifex-core
roleRef:
  kind: ClusterRole
  name: opifex-gpu-access
  apiGroup: rbac.authorization.k8s.io
