apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: opifex-collaborators
  name: external-collaborator
  labels:
    opifex.local/research-group: "collaborators"
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps"]
    verbs: ["get", "list", "watch", "create"]
    resourceNames: ["shared-*", "public-*"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create"]
    resourceNames: ["inference-*"]
  - apiGroups: ["opifex.local"]
    resources: ["inferencejobs", "sharedmodels"]
    verbs: ["get", "list", "watch", "create"]
